on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull code
        run: git pull
        working-directory: ~/Deb\ Tour/DebTour-backend
      
      - name: Build docker compose
        run: docker-compose up -d --build
        working-directory: ~/Deb\ Tour/DebTour-backend
