on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Stop existing containers
        run: docker-compose down
        
      - name: Build docker compose
        run: docker-compose up -d --build
