on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Stop existing containers
        run: docker-compose down

      - name: Download Go dependencies
        run: go mod download

      - name: Build Go
        run: go build -o main .

      - name: Build docker compose
        run: docker-compose up -d

      - name: Run Go
        run: ./main
